In [93]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
import numpy as np

X, y, tcoef = make_regression(n_samples=100, n_features=1000, n_informative=2, noise=30.0,
                              coef=True, 
                              random_state=10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

basemodel = LinearRegression()
basemodel.fit(X_train, y_train)

r2_score(y_test, basemodel.predict(X_test))

-0.35229725406329826

In [94]:
np.argwhere(tcoef != 0).ravel()

array([232, 900])

In [95]:
model = PLSRegression(n_components=2)
model.fit(X_train, y_train)

PLSRegression()

In [96]:
model.x_weights_

array([[ 0.03677149, -0.0650503 ],
       [-0.07889841,  0.02267463],
       [ 0.01496268,  0.03689141],
       ...,
       [-0.03192611,  0.01409466],
       [ 0.01408655, -0.0131498 ],
       [-0.02806488,  0.05403946]])

In [97]:
model.predict(X_test)

array([[   8.36365525],
       [ -50.90327304],
       [ -45.27937288],
       [ -37.67317241],
       [ -31.86281286],
       [ -14.18228458],
       [ -98.91356285],
       [ -53.55247097],
       [  -9.25460169],
       [ -18.58262981],
       [ -24.42847737],
       [ -20.60946082],
       [ -10.52170822],
       [ -79.40211243],
       [ -41.99350859],
       [ -37.74002207],
       [-102.95452322],
       [ -65.6222381 ],
       [ -70.61285436],
       [ -59.15709097],
       [ -16.51415492],
       [ -34.84045166],
       [   3.69357298],
       [ -95.11071066],
       [-106.67751853]])

In [101]:
np.linalg.norm(V, axis=0)

array([1., 1.])

In [99]:
L.T @ V

array([[ 1.00000000e+00, -2.38076261e-01],
       [ 1.06685494e-16,  1.00000000e+00]])

In [98]:
X_test_scaled = (X_test - model._x_mean) / model._x_std 
V = model.x_weights_
L = model.x_loadings_
R = V @ np.linalg.pinv(L.T @ V)

y_pred_test_untr = X_test_scaled @ R # PLS prediction
# y_pred_test_kdm = X_test_scaled @ V / (V.T @ V) # KDM prediction

In [86]:
# np.isclose(y_pred_test_untr.ravel(), y_pred_test_kdm.ravel())

In [88]:
# np.corrcoef(y_pred_test_untr.ravel(), model.predict(X_test).ravel() )

In [43]:
np.corrcoef(y_pred_test_2.ravel(), y_pred_test_untr.ravel())

array([[1., 1.],
       [1., 1.]])

In [33]:
np.corrcoef(V.ravel(), L.ravel())

array([[1.        , 0.96908728],
       [0.96908728, 1.        ]])

array([[1., 1.],
       [1., 1.]])

In [14]:
model.x_weights_

array([[ 0.05364706],
       [ 0.0033299 ],
       [ 0.60336176],
       [ 0.07792432],
       [ 0.00109431],
       [ 0.7887291 ],
       [ 0.02793724],
       [-0.01935501],
       [-0.00765809],
       [ 0.06070222]])

In [15]:
model.x_loadings_

array([[ 0.09381422],
       [ 0.01737908],
       [ 0.59791032],
       [ 0.13438696],
       [ 0.00802706],
       [ 0.77580919],
       [ 0.08062372],
       [-0.03558635],
       [-0.0427291 ],
       [ 0.1400372 ]])